program: train.py
name: sweepdemo
project: "corrupt_mnist"  # change this
entity: asmusdals-technical-univeristy-of-denmark  # change this
method: random #skulle tilf√∏jes apparently
metric:
    goal: minimize
    name: train_loss
parameters:
    learning_rate:
        min: 0.0001
        max: 0.1
        distribution: log_uniform
    batch_size:
        values: [16, 32, 64]
    epochs:
        values: [5, 10, 15]

command:
  - ${env}
  - uv
  - run
  - train
  - --lr=${lr}
  - --batch_size=${batch_size}
  - --epochs=${epochs}
  
run_cap: 10


